# Generated by Django 5.1.1 on 2024-09-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersinfo', '0003_alter_user_options_user_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-score'], 'verbose_name': 'Player'},
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_images/me_image.jpg', upload_to='profile_images/'),
        ),
    ]
