# Generated by Django 5.1.1 on 2024-09-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersinfo', '0006_players_playerhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
    ]
