# Generated by Django 5.1.1 on 2024-09-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersinfo', '0007_rename_players_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-score'], 'verbose_name': 'NewPlayer'},
        ),
    ]
