# Generated by Django 5.1.1 on 2024-09-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('score', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('online', models.BooleanField(default=True)),
            ],
        ),
    ]
