# Generated by Django 5.1.1 on 2024-09-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersinfo', '0005_user_gender_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_Name', models.CharField(max_length=50, verbose_name='Nan')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Nan')),
                ('Previous_Games', models.ManyToManyField(to='usersinfo.players')),
            ],
        ),
    ]
